# NumPy Numerical Python

# 50 NumPy Attributes and Codings



# Importing Libraries

In [192]:
import numpy as np

# 1. Creating a 1D array from 0 to 5

In [193]:
array = np.arange(0,5)

In [194]:
array

array([0, 1, 2, 3, 4])

# 2. Creating a 1D array of 5x5

In [195]:
array = np.ones((5,5))

In [196]:
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Creating Bool Array

In [197]:
array = np.full((2,2),False,dtype=bool)

In [198]:
array

array([[False, False],
       [False, False]])

# 4. Extracting Elements that satisfy condition


In [199]:
array = np.array([0,1,2,3,4,5,6,7,8,9,10,123,4,5,67,2231,345])

In [200]:
array[array%2==1]

array([   1,    3,    5, ...,   67, 2231,  345])

# 5. Replacing Elements that satisfy condition

In [201]:
array = np.array([0,2,3,456,1,23,45,4,123,1345,123.45,3125])

In [202]:
array[array%5==0]=0.0

In [203]:
array

array([  0.  ,   2.  ,   3.  , ...,   0.  , 123.45,   0.  ])

# 6.  Replacing Elements that satisfy condition without affecting original array

In [204]:
org = np.array([0,3,5,6,7,12,60,80,70,50,37,100])

In [205]:
array=np.where(org%5==0,"Ok",org)

In [206]:
array

array(['Ok', '3', 'Ok', ..., 'Ok', '37', 'Ok'], dtype='<U11')

# 7. Reshaping 1D into 2D array

In [207]:
array =np.arange(0,10)
array= array.reshape(2,-1)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. Stacking Two Arrays vertically

In [208]:
a=np.arange(0,10).reshape(2,-1)
b=5*np.ones((1,10)).reshape(2,-1)
new=np.vstack([a,b])
new

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# 9. Stacking Two Arrays Horizontally

In [209]:
new=np.hstack([a,b])
new

array([[0., 1., 2., ..., 5., 5., 5.],
       [5., 6., 7., ..., 5., 5., 5.]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [210]:
array=np.array([1,2,3])

In [211]:
np.r_[np.repeat(array,3),np.tile(array,3)]

array([1, 1, 1, ..., 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [212]:
array_1=np.arange(0,10)


In [213]:
array_2=np.arange(0,20,2)


In [214]:
np.intersect1d(array_1,array_2)

array([0, 2, 4, 6, 8])

# 12. How to remove from one array those items that exist in another?

In [215]:
array_1=np.arange(0,10)
array_2=np.arange(0,10,2)

In [216]:
np.setdiff1d(array_1,array_2)

array([1, 3, 5, 7, 9])

# 13. How to get the positions where elements of two arrays match?

In [217]:
array_1=np.array([0,2,3,4,5,6,7,8,9,1])
array_2=np.array([0,3,3,4,6,7,7,8,9,9])
np.where(array_1==array_2)

(array([0, 2, 3, 6, 7, 8], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [218]:
array=np.array([1,2,3,4,6,100,3,4,56])
array[(array>3)&(array<5)]

array([4, 4])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [219]:
def arr(x,y):
    if x>y:
        return x
    else:
        return y
    

In [220]:
pair = np.vectorize(arr,otypes=[float])


In [221]:
array_1=np.array([1,2,3,4,5,6])
array_2=np.array([2,1,2,3,4,5])
pair(array_1,array_2)

array([2., 2., 3., 4., 5., 6.])

# 16. How to swap two columns in a 2d numpy array?

In [222]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [223]:
array[:,[1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

# 17. How to swap two rows in a 2d numpy array?

In [224]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
array[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [226]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [227]:
array[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. How to reverse the columns of a 2D array?

In [228]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
array[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [230]:
array=np.random.uniform(5,10,size=(5,3))

In [231]:
array

array([[7.75010551, 9.94535696, 5.27373226],
       [8.0850361 , 5.56165518, 7.31244004],
       [8.67435186, 6.68041101, 7.73067911],
       [9.76290567, 5.57077305, 9.9117531 ],
       [8.71197433, 9.2403672 , 8.6613022 ]])

# 21. How to limit the number of items printed in output of numpy array?

In [232]:
array = np.arange(10)

In [233]:
array

array([0, 1, 2, ..., 7, 8, 9])

In [234]:
np.set_printoptions(threshold=6)
array

array([0, 1, 2, ..., 7, 8, 9])

# 22. How to extract a particular column from 1D array of tuples?

In [235]:
#Q. Extract the text column species from the 1D iris imported in previous question.

In [236]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url,delimiter=",",dtype=None)
print(iris)

[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') ...
 (6.5, 3. , 5.2, 2. , b'Iris-virginica')
 (6.2, 3.4, 5.4, 2.3, b'Iris-virginica')
 (5.9, 3. , 5.1, 1.8, b'Iris-virginica')]


<ipython-input-236-5382bb1e3e54>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris=np.genfromtxt(url,delimiter=",",dtype=None)


In [237]:
b=[]
for i in range(len(iris)):
    a=iris[i][4]
    b.append(a)
array=np.array(b)
array

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S18')

# 23. How to convert a 1d array of tuples to a 2d numpy array?

In [238]:
iris=np.genfromtxt(url,delimiter=",",dtype="float",usecols=[0,1,2])
iris[:4]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5]])

# 24. How to compute the mean, median, standard deviation of a numpy array?

In [239]:
sepallength=np.genfromtxt(url,delimiter=",",dtype="float",usecols=[0])

In [240]:
#mean
m=np.mean(sepallength)
m

5.843333333333334

In [241]:
#median
md=np.median(sepallength)
md

5.8

In [242]:
#standard deviation
st=np.std(sepallength)
st

0.8253012917851409

In [243]:
print(round(m,4),round(md,4),round(st,4))

5.8433 5.8 0.8253


# 25. How to normalize an array so the values range exactly between 0 and 1?

In [244]:
S_max=sepallength.max()
S_min=sepallength.min()

In [245]:
#Formula
S=(sepallength-S_min)/sepallength.ptp()
S

array([0.22222222, 0.16666667, 0.11111111, ..., 0.61111111, 0.52777778,
       0.44444444])

# 26. How to compute the softmax score?

In [246]:
def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x/e_x.sum(axis=0)

In [247]:
softmax(sepallength)

array([0.00221959, 0.00181724, 0.00148783, ..., 0.00900086, 0.006668  ,
       0.00493978])

# 27. How to find the percentile scores of a numpy array?

In [248]:
np.percentile(sepallength,q=[5,75])

array([4.6, 6.4])

# 28. How to find the position of missing values in numpy array?

In [249]:
iris_2d=np.genfromtxt(url,delimiter=",",dtype="float",usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan

In [250]:
np.where(np.isnan(iris_2d[:,0]))

(array([ 32,  36,  42, ...,  85,  93, 126], dtype=int64),)

# 29. How to find the number of missing values in numpy array?

In [251]:
np.isnan(iris_2d[:,0]).sum()

8

# 30. How to filter a numpy array based on two or more conditions?

In [252]:
condition=(iris_2d[:,2]>2.0)&(iris_2d[:,0]<10)
a=iris_2d[condition]
a

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [5.5, 2.3, 4. , 1.3],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

# 31. How to know that contain a missing value from a numpy array?

In [253]:
np.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# 32. How to find the correlation between two columns of a numpy array?

In [254]:
iris=np.genfromtxt(url,delimiter=",",dtype="float",usecols=[0,1,2,3])

In [255]:
np.corrcoef(iris[:,0],iris[:,2])[0,1]

0.8717541573048709

# 33. How to find if a given array has any null values?

In [256]:
np.isnan(iris).any()

False

# 34. How to find the count of unique values in a numpy array?

In [257]:
iris=np.genfromtxt(url,delimiter=",",dtype="object")
names=("sepallength","sepalwidth","petallength","petalwidth","sepcies")

In [258]:
a=[]
for i in range(len(iris)):
    b=iris[i]
    a.append(b)
np.unique(a,return_counts=True)

(array([b'0.1', b'0.2', b'0.3', ..., b'Iris-setosa', b'Iris-versicolor',
        b'Iris-virginica'], dtype=object),
 array([ 6, 28,  7, ..., 50, 50, 50], dtype=int64))

# 35. How to convert an array of arrays into a flat 1d array??

In [259]:
array1=np.arange(1,3)
array2=np.arange(6,8)
array3=np.arange(10,12)

In [260]:
arrays_2d=np.array([array1,array2,array3])
arrays_2d

array([[ 1,  2],
       [ 6,  7],
       [10, 11]])

In [261]:
array_1d=np.concatenate(arrays_2d)
array_1d

array([ 1,  2,  6,  7, 10, 11])

# 36. How to rank items in an array using numpy?

In [262]:
np.random.seed(10)
array=np.random.randint(10,size=20)
array

array([9, 4, 0, ..., 8, 1, 8])

In [263]:
print(array.argsort().argsort())

[19  8  1 ... 13  6 14]


# 37. How to rank items in a multidimensional array using numpy?

In [264]:
np.random.seed(10)
array=np.random.randint(14,size=[5,5])
array

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9],
       [ 0, 10,  8,  6,  4],
       [ 3,  0,  4, 11,  6]])

In [265]:
array.ravel().argsort().argsort().reshape(array.shape)

array([[14, 24,  8,  0,  4],
       [20, 21, 15, 23,  2],
       [22,  5, 18, 13, 16],
       [ 3, 17, 12, 11,  9],
       [ 6,  1,  7, 19, 10]], dtype=int64)

# 38. How to find the maximum value in each row of a numpy array 2d?

In [266]:
np.random.seed(100)
array=np.random.randint(1,14,size=[4,4])
array

array([[ 9,  9,  4,  8],
       [ 8,  1, 11,  5],
       [ 3,  6,  3,  3],
       [ 3,  2,  1,  9]])

In [267]:
np.amax(array,axis=1)

array([ 9, 11,  6,  9])

# 39. How to find the duplicate records in a numpy array?

In [268]:
array=np.random.randint(0,17,20)
array

array([15,  4, 11, ...,  7, 16,  2])

In [269]:
true =np.full(array.shape[0],True)
unique=np.unique(array,return_index=True)[1]
true[unique]=False

In [270]:
true

array([False, False, False, ...,  True,  True,  True])

# 40. How to compute the euclidean distance between two arrays?


In [271]:
array1=np.array([1,2,3,5,6])
array2=np.array([3,4,5,6,8])

In [272]:
dist=np.linalg.norm(array1-array2)
dist
    

4.123105625617661

# 41. How to find the index of n'th repetition of an item in an array


In [273]:
array=np.array([1,25,6,7,1,3,4,5,1,1,2,3,4,1,2,3])
n=3

In [274]:
np.where(array==1)[0][n-1]

8

# 42. How to create a numpy array sequence given only the starting point, length and the step?

In [275]:
length=60
start=6
step=5
def seq(a,b,c):
    finish=a+(b*c)
    return np.arange(a,finish,c)

In [276]:
seq(start,length,step)

array([  6,  11,  16, ..., 291, 296, 301])

# 43.Basic Operations

In [277]:
array1=np.arange(0,5)
array2=np.arange(5,10)

In [278]:
array3=array2-array1
array3

array([5, 5, 5, 5, 5])

In [279]:
array4=array2*array1
array4

array([ 0,  6, 14, 24, 36])

In [280]:
array5=array1/array2
array5

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

# 44. Universal Functions

In [281]:
array1=np.arange(10)
np.exp(array1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, ...,
       1.09663316e+03, 2.98095799e+03, 8.10308393e+03])

In [282]:
np.sqrt(array1)

array([0.        , 1.        , 1.41421356, ..., 2.64575131, 2.82842712,
       3.        ])

# 45. Indexing, Slicing and Iterating

In [283]:
 array=np.arange(20)*3

In [284]:
array

array([ 0,  3,  6, ..., 51, 54, 57])

In [285]:
array[0:5]

array([ 0,  3,  6,  9, 12])

In [286]:
array[3:7]=True

In [287]:
array

array([ 0,  3,  6, ..., 51, 54, 57])

In [288]:
array[3:7]

array([1, 1, 1, 1])

In [289]:
array[::-1]

array([57, 54, 51, ...,  6,  3,  0])

# 46. Shape of array

In [290]:
array=np.random.randint(1,5,size=[7,7])

In [291]:
array.shape

(7, 7)

# 47. No copy 

In [292]:
 array=np.random.randint(1,3,size=[6,7])
array1=array
array1 is array

True

In [293]:
def f(x):
    print(id(x))
    

In [294]:
f(array1) #identifier

283968441360


In [295]:
f(array)

283968441360


# 48.  View or Shallow copy

In [296]:
array3=array1.view()

In [297]:
array3 is array1 

False

In [298]:
array3.base is array1

True

# 49. Deep Copy

In [299]:
array4=array1.copy()

In [300]:
array4 is array1

False

In [301]:
array4.base is array1

False

In [302]:
array4[1,1]=819

In [303]:
array4

array([[  1,   2,   1, ...,   1,   2,   2],
       [  1, 819,   2, ...,   2,   2,   1],
       [  1,   1,   1, ...,   1,   2,   1],
       [  2,   2,   1, ...,   1,   1,   1],
       [  1,   1,   1, ...,   1,   2,   2],
       [  1,   1,   1, ...,   2,   2,   2]])

In [304]:
array1

array([[1, 2, 1, ..., 1, 2, 2],
       [1, 1, 2, ..., 2, 2, 1],
       [1, 1, 1, ..., 1, 2, 1],
       [2, 2, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 2, 2],
       [1, 1, 1, ..., 2, 2, 2]])

# Sum of all elements in two dimensional array

In [305]:
array=np.random.randint(1,7,size=[7,7])

In [306]:
array.sum()

175